hotkey: "ctrl+shift+space"
engine: "faster-whisper"     # "whispercpp" möglich
model: "medium"              # small/medium/large-v3
device: "cuda"               # "auto", "cuda", "cpu"
language: "de"               # "auto" für automatischerkennung
insert_mode: "type"          # "type" | "clipboard"
vad:
  enable: true
  aggressiveness: 2          # 0..3
  min_speech_ms: 300
  max_silence_ms: 800
chunk:
  seconds: 0.8
  overlap: 0.2
punctuate: true
log_transcripts: false
