chunk:
  overlap: 0.2
  seconds: 0.8
device: cuda
engine: faster-whisper
hotkey: ctrl+shift+space
insert_mode: type
language: de
log_transcripts: false
model: medium
punctuate: true
vad:
  aggressiveness: 2
  enable: true
  max_silence_ms: 800
  min_speech_ms: 300
